### ISSUE TITLE
Repo is alive ?

### ISSUE THREAD

**Issue by thaiat** [enginespot/js-beautify-sublime#28]
Is this repo still alive ?

**Comment by jabyrd3** [comment]
Doesn't look like it. Plugin on package manager stopped working as well.

'Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "jsbeautify in /Users/admin.jbyrd/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package", line 72
    print "hello"
                ^
SyntaxError: invalid syntax
'

**Comment by larryprice** [comment]
That should be an easy fix - just need to change the line `print "hello"` to use `print("hello")`. The line without parens is invalid Python 3 syntax.

**Comment by enginespot** [comment]
sorry to reply delay 

yes , it is alive , but currently I am busy with another project , so it is a bit delay update , but it is very welcome anyone pull request

Thanks.

**Comment by a0viedo** [comment]
It doesn't seems like it. There's a PR from last year with no activity https://github.com/enginespot/js-beautify-sublime/pull/12.
