### ISSUE TITLE
No longer working with current build of Sublime 3 - Stable Branch b3114

### ISSUE THREAD

**Issue by bob-fm** [enginespot/js-beautify-sublime#47]
Sublime Text - Build 3114, Stable Channel
Plugin - v2016.09.07.13.45.32; github.com/enginespot/js-beautify-sublime

The following is in the console: 
```
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "jsbeautify in C:\Users\defNotMe\AppData\Roaming\Sublime Text 3\Installed Packages\Javascript Beautify.sublime-package", line 115, in run
  File "jsbeautify in C:\Users\defNotMe\AppData\Roaming\Sublime Text 3\Installed Packages\Javascript Beautify.sublime-package", line 190, in format_whole_file
  File "C:\Users\defNotMe\AppData\Roaming\Sublime Text 3\Installed Packages\Javascript Beautify.sublime-package\libs\js-beautify\python\jsbeautifier\__init__.py", line 246, in beautify
  File "C:\Users\defNotMe\AppData\Roaming\Sublime Text 3\Installed Packages\Javascript Beautify.sublime-package\libs\js-beautify\python\jsbeautifier\__init__.py", line 393, in __init__
  File "C:\Users\defNotMe\AppData\Roaming\Sublime Text 3\Installed Packages\Javascript Beautify.sublime-package\libs\js-beautify\python\jsbeautifier\__init__.py", line 162, in __init__
ImportError: No module named 'six'
```

**Comment by antda** [comment]
Yeah I got the same problem. Stopped working yesterday
Build 3114

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "jsbeautify in /Users/anton/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package", line 115, in run
  File "jsbeautify in /Users/anton/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package", line 190, in format_whole_file
  File "/Users/anton/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package/libs/js-beautify/python/jsbeautifier/__init__.py", line 246, in beautify
  File "/Users/anton/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package/libs/js-beautify/python/jsbeautifier/__init__.py", line 393, in __init__
  File "/Users/anton/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package/libs/js-beautify/python/jsbeautifier/__init__.py", line 162, in __init__
ImportError: No module named 'six'`

**Comment by wickedsp1d3r** [comment]
Same problem here too.

**Comment by emmea90** [comment]
Same here

**Comment by bob-fm** [comment]
There is an issue with the package, as served through the package manager. 

The following steps address the issue, e.g pull it straight from this branch, as stated in #39. 

```
Select Package Control and then Add Repository
Copy/Paste/Enter the URL: https://github.com/fyelles/js-beautify-sublime and hit enter
Select Package Control and Remove Package: Javascript beautify
Select Package Control and Install Package (Note Different Name): js-beautify-sublime
```
